import { FormEvent, useState, useEffect } from 'react';

const api = import.meta.env.VITE_API_URL ?? '';
const DAYS = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'];
const MONTHS = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const services = [{ name: 'Corte clássico', price: 'R$ 45' }, { name: 'Corte + barba', price: 'R$ 75' }, { name: 'Barba completa', price: 'R$ 40' }, { name: 'Pezinho', price: 'R$ 20' }];
type Slot = { id: string; slot_date: string; slot_time: string };
type Appointment = { id: string; customer_name: string; phone: string; service: string; appointment_at: string; status: 'PENDING' | 'COMPLETED' | 'NO_SHOW' };
const labels = { PENDING: 'Pendente', COMPLETED: 'Feito', NO_SHOW: 'Não realizado' };
const times = Array.from({length:31},(_,i)=>{const h=7+Math.floor(i/2);const m=i%2*30;return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')});
const today = new Date(); const todayStr = today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');
function daysInMonth(m:number,y:number){return new Date(y,m+1,0).getDate()}
function firstDow(m:number,y:number){return(new Date(y,m,1).getDay()+6)%7}

export default function Admin() {
  const [password, setPassword] = useState(''); const [logged, setLogged] = useState(false); const [items, setItems] = useState<Appointment[]>([]); const [slots, setSlots] = useState<Slot[]>([]); const [error, setError] = useState(''); const [tab, setTab] = useState<'agenda'|'horarios'>('agenda');
  const [cm, setCm] = useState(today.getMonth()); const [cy, setCy] = useState(today.getFullYear()); const [selDate, setSelDate] = useState(''); const [daySlots, setDaySlots] = useState<Slot[]>([]);
  const dim = daysInMonth(cm,cy); const fdow = firstDow(cm,cy);
  const daysArr:{n:number,off:boolean,ok:boolean}[] = [];
  for (let i=0;i<fdow;i++) daysArr.push({n:0,off:true,ok:false});
  for (let d=1;d<=dim;d++){const ds=cy+'-'+String(cm+1).padStart(2,'0')+'-'+String(d).padStart(2,'0');daysArr.push({n:d,off:false,ok:true});}
  const priceOf = (s:string) => { const sv = services.find(x => x.name === s); return sv ? sv.price : ''; };
  async function load(){const r=await fetch(`${api}/api/appointments`,{credentials:'include'});if(!r.ok)throw new Error('Erro');setItems(await r.json());}
  async function login(e:FormEvent){e.preventDefault();setError('');const r=await fetch(`${api}/api/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({password})});if(!r.ok){setError('Senha inválida.');return;}setLogged(true);await load();}
  async function change(id:string,m:'PATCH'|'DELETE',s?:string){const r=await fetch(`${api}/api/appointments/${id}`,{method:m,headers:{'Content-Type':'application/json'},credentials:'include',body:s?JSON.stringify({status:s}):undefined});if(!r.ok){setError('Erro');return;}await load();}
  async function loadMonthSlots(){const r=await fetch(`${api}/api/admin/slots?month=${cy}-${String(cm+1).padStart(2,'0')}`,{credentials:'include'});if(r.ok)setSlots(await r.json());}
  async function loadDaySlots(d:string){const r=await fetch(`${api}/api/admin/slots?date=${d}`,{credentials:'include'});if(r.ok)setDaySlots(await r.json());}
  async function toggleSlot(d:string,t:string){const existing=daySlots.find(s=>s.slot_date===d&&s.slot_time.slice(0,5)===t);if(existing){await fetch(`${api}/api/admin/slots/${existing.id}`,{method:'DELETE',credentials:'include'});}else{await fetch(`${api}/api/admin/slots`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({slot_date:d,slot_time:t+':00'})});}await loadDaySlots(d);await loadMonthSlots();}
  useEffect(()=>{if(tab==='horarios'&&!selDate)loadMonthSlots()},[tab,cm,cy,selDate]);
  useEffect(()=>{if(selDate)loadDaySlots(selDate);},[selDate]);
  if(!logged)return<main className="grid min-h-screen place-items-center px-6"><form onSubmit={login} className="w-full max-w-sm border-t-4 border-[#bd4f2d] bg-[#e2ddd2] p-8 shadow-xl"><a href="/" className="font-display text-3xl font-bold">LÂMINA<span className="text-[#bd4f2d]">.</span></a><h1 className="mt-12 font-display text-4xl uppercase">Administração</h1><p className="mt-2 text-sm text-[#5b574f]">Entre para acompanhar os atendimentos.</p><label className="mt-8 block text-sm">Senha<input autoFocus required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-7 w-full bg-[#1d1d1b] py-3 font-mono text-xs uppercase tracking-widest text-white">Entrar</button>{error&&<p className="mt-4 text-sm text-[#bd4f2d]">{error}</p>}</form></main>;
  return<main className="mx-auto min-h-screen max-w-6xl px-6 py-8"><header className="flex items-end justify-between border-b-2 border-[#1d1d1b] pb-6"><div><a href="/" className="font-display text-3xl font-bold">LÂMINA<span className="text-[#bd4f2d]">.</span></a><div className="mt-4 flex gap-4">{(['agenda','horarios']as const).map(t=><button key={t} onClick={()=>{setTab(t);if(t==='horarios'){setSelDate('');loadMonthSlots();}}} className={`font-mono text-xs uppercase tracking-wider ${tab===t?'text-[#1d1d1b] underline':'text-[#5b574f]'}`}>{t==='agenda'?'Agenda':'Horários'}</button>)}</div></div><button onClick={tab==='agenda'?load:()=>{setSelDate('');loadMonthSlots();}} className="font-mono text-xs uppercase underline">Atualizar</button></header>{error&&<p className="mt-6 text-[#bd4f2d]">{error}</p>}
  {tab==='agenda'?<div className="mt-8 overflow-x-auto"><table className="w-full min-w-200 text-left"><thead className="font-mono text-xs uppercase tracking-wider text-[#5b574f]"><tr><th className="pb-4">Cliente</th><th className="pb-4">Contato</th><th className="pb-4">Serviço</th><th className="pb-4">Valor</th><th className="pb-4">Horário</th><th className="pb-4">Status</th><th className="pb-4">Ações</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-[#c9c1b4]"><td className="py-4 font-semibold">{item.customer_name}</td><td className="py-4">{item.phone}</td><td className="py-4">{item.service}</td><td className="py-4 font-mono">{priceOf(item.service)}</td><td className="py-4">{new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(new Date(item.appointment_at))}</td><td className="py-4"><span className="font-mono text-xs uppercase">{labels[item.status]}</span></td><td className="py-4"><div className="flex gap-2"><button title="Marcar como feito" onClick={()=>change(item.id,'PATCH','COMPLETED')} className="border border-[#1d1d1b] px-2 py-1 text-xs">Feito</button><button title="Marcar como não realizado" onClick={()=>change(item.id,'PATCH','NO_SHOW')} className="border border-[#1d1d1b] px-2 py-1 text-xs">Não veio</button><button title="Excluir agendamento" onClick={()=>change(item.id,'DELETE')} className="border border-[#bd4f2d] px-2 py-1 text-xs text-[#bd4f2d]">Excluir</button></div></td></tr>)}</tbody></table>{items.length===0&&<p className="py-12 text-center text-[#5b574f]">Nenhum agendamento.</p>}</div>
   :!selDate?<div className="mt-8 max-w-md mx-auto"><div className="flex items-center justify-between mb-4"><button type="button" onClick={()=>{if(cm===0){setCm(11);setCy(cy-1)}else setCm(cm-1)}} className="px-3 py-1 font-mono text-sm">&lt;</button><span className="font-display text-2xl uppercase">{MONTHS[cm]} {cy}</span><button type="button" onClick={()=>{if(cm===11){setCm(0);setCy(cy+1)}else setCm(cm+1)}} className="px-3 py-1 font-mono text-sm">&gt;</button></div><div className="grid grid-cols-7 gap-1 text-center">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><div key={d} className="font-mono text-xs text-[#5b574f] py-1">{d}</div>)}{daysArr.map((d,i)=>{const ds=cy+'-'+String(cm+1).padStart(2,'0')+'-'+String(d.n).padStart(2,'0');const hasSlots=slots.some(s=>s.slot_date===ds);return<button key={i} type="button" onClick={()=>d.ok&&setSelDate(ds)} className={`py-2 text-sm font-mono rounded transition ${d.off?'':hasSlots?'bg-[#bd4f2d] text-white font-bold hover:bg-[#913a20]':'bg-[#c9c1b4] hover:bg-[#bdb7ab]'} ${!d.off&&d.n===today.getDate()&&cm===today.getMonth()&&cy===today.getFullYear()?'ring-2 ring-[#1d1d1b]':''}`}>{d.off?'':d.n}</button>})}</div></div>
   :<div className="mt-8"><button onClick={()=>setSelDate('')} className="font-mono text-xs uppercase underline mb-6 block">&larr; Voltar ao calendário</button><h2 className="font-display text-3xl uppercase mb-6">{new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'numeric',month:'long',year:'numeric'}).format(new Date(selDate+'T12:00:00-03:00'))}</h2><div className="overflow-x-auto"><table className="w-full min-w-175 text-left"><thead className="font-mono text-xs uppercase tracking-wider text-[#5b574f]"><tr><th className="pb-4">Horário</th><th className="pb-4">Bloqueado</th></tr></thead><tbody>{times.map(t=>{const on=daySlots.some(s=>s.slot_time.slice(0,5)===t);return<tr key={t} className="border-t border-[#c9c1b4]"><td className="py-2 pr-4 font-mono text-sm">{t}</td><td className="py-2"><button onClick={()=>toggleSlot(selDate,t)} className={`w-24 py-2 text-xs font-mono uppercase tracking-wider border transition ${on?'bg-[#bd4f2d] text-white border-[#bd4f2d]':'bg-transparent text-[#c9c1b4] border-[#c9c1b4] hover:border-[#5b574f]'}`}>{on?'BLOQ':'—'}</button></td></tr>})}</tbody></table></div></div>}</main>;
}
