import { FormEvent, useState } from 'react';

const api = import.meta.env.VITE_API_URL ?? '/api';
type Appointment = { id: string; customer_name: string; phone: string; service: string; appointment_at: string; status: 'PENDING' | 'COMPLETED' | 'NO_SHOW' };
const labels = { PENDING: 'Pendente', COMPLETED: 'Feito', NO_SHOW: 'Não realizado' };

export default function Admin() {
  const [password, setPassword] = useState(''); const [logged, setLogged] = useState(false); const [items, setItems] = useState<Appointment[]>([]); const [error, setError] = useState('');
  async function load() { const response = await fetch(`${api}/api/appointments`, { credentials: 'include' }); if (!response.ok) throw new Error('Não foi possível carregar os agendamentos.'); setItems(await response.json()); }
  async function login(event: FormEvent) { event.preventDefault(); setError(''); const response = await fetch(`${api}/api/admin/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: JSON.stringify({ password }) }); if (!response.ok) { setError('Senha inválida.'); return; } setLogged(true); await load(); }
  async function change(id: string, method: 'PATCH' | 'DELETE', status?: string) { const response = await fetch(`${api}/api/appointments/${id}`, { method, headers: { 'Content-Type': 'application/json' }, credentials: 'include', body: status ? JSON.stringify({ status }) : undefined }); if (!response.ok) { setError('Não foi possível salvar a alteração.'); return; } await load(); }
  if (!logged) return <main className="grid min-h-screen place-items-center px-6"><form onSubmit={login} className="w-full max-w-sm border-t-4 border-[#bd4f2d] bg-[#e2ddd2] p-8 shadow-xl"><a href="/" className="font-display text-3xl font-bold">LÂMINA<span className="text-[#bd4f2d]">.</span></a><h1 className="mt-12 font-display text-4xl uppercase">Administração</h1><p className="mt-2 text-sm text-[#5b574f]">Entre para acompanhar os atendimentos.</p><label className="mt-8 block text-sm">Senha<input autoFocus required type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><button className="mt-7 w-full bg-[#1d1d1b] py-3 font-mono text-xs uppercase tracking-widest text-white">Entrar</button>{error && <p className="mt-4 text-sm text-[#bd4f2d]">{error}</p>}</form></main>;
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-8"><header className="flex items-end justify-between border-b-2 border-[#1d1d1b] pb-6"><div><a href="/" className="font-display text-3xl font-bold">LÂMINA<span className="text-[#bd4f2d]">.</span></a><h1 className="mt-8 font-display text-5xl uppercase">Agenda</h1></div><button onClick={() => load()} className="font-mono text-xs uppercase underline">Atualizar</button></header>{error && <p className="mt-6 text-[#bd4f2d]">{error}</p>}<div className="mt-8 overflow-x-auto"><table className="w-full min-w-175 text-left"><thead className="font-mono text-xs uppercase tracking-wider text-[#5b574f]"><tr><th className="pb-4">Cliente</th><th className="pb-4">Contato</th><th className="pb-4">Serviço</th><th className="pb-4">Horário</th><th className="pb-4">Status</th><th className="pb-4">Ações</th></tr></thead><tbody>{items.map(item => <tr key={item.id} className="border-t border-[#c9c1b4]"><td className="py-4 font-semibold">{item.customer_name}</td><td className="py-4">{item.phone}</td><td className="py-4">{item.service}</td><td className="py-4">{new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', dateStyle: 'short', timeStyle: 'short' }).format(new Date(item.appointment_at))}</td><td className="py-4"><span className="font-mono text-xs uppercase">{labels[item.status]}</span></td><td className="py-4"><div className="flex gap-2"><button title="Marcar como feito" onClick={() => change(item.id, 'PATCH', 'COMPLETED')} className="border border-[#1d1d1b] px-2 py-1 text-xs">Feito</button><button title="Marcar como não realizado" onClick={() => change(item.id, 'PATCH', 'NO_SHOW')} className="border border-[#1d1d1b] px-2 py-1 text-xs">Não veio</button><button title="Excluir agendamento" onClick={() => change(item.id, 'DELETE')} className="border border-[#bd4f2d] px-2 py-1 text-xs text-[#bd4f2d]">Excluir</button></div></td></tr>)}</tbody></table>{items.length === 0 && <p className="py-12 text-[#5b574f]">Nenhum agendamento ainda.</p>}</div></main>;
}
