import { useEffect, useState } from 'react';
import { Scissors } from 'lucide-react';
import Admin from './Admin';

const api = import.meta.env.VITE_API_URL ?? '/api';
const services = [{ name: 'Corte clássico', price: 'R$ 45' }, { name: 'Corte + barba', price: 'R$ 75' }, { name: 'Barba completa', price: 'R$ 40' }, { name: 'Pezinho', price: 'R$ 20' }];
function brasiliaNow() { return new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', weekday: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date()); }
function openNow() { const p = new Intl.DateTimeFormat('en-US', { timeZone: 'America/Sao_Paulo', weekday: 'short', hour: 'numeric', hour12: false }).formatToParts(new Date()); const day = p.find(x => x.type === 'weekday')?.value; const hour = Number(p.find(x => x.type === 'hour')?.value); return day !== 'Sat' && day !== 'Sun' && hour >= 9 && hour < 19; }
export default function App() {
  if (window.location.pathname === '/admin') return <Admin />;
  const [clock, setClock] = useState(brasiliaNow()); const [isOpen, setIsOpen] = useState(openNow()); const [form, setForm] = useState({ name: '', phone: '', service: services[0].name, appointmentAt: '' }); const [message, setMessage] = useState('');
  useEffect(() => { const id = window.setInterval(() => { setClock(brasiliaNow()); setIsOpen(openNow()); }, 1000); return () => clearInterval(id); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage('Enviando...'); const res = await fetch(`${api}/api/appointments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, appointmentAt: new Date(form.appointmentAt).toISOString() }) }); const data = await res.json(); setMessage(res.ok ? 'Agendamento recebido. O pagamento é feito após o atendimento.' : data.error); if (res.ok) setForm({ name: '', phone: '', service: services[0].name, appointmentAt: '' }); }
  return <main>
    <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><a className="font-display text-3xl font-bold tracking-tight" href="#inicio">LÂMINA<span className="text-[#bd4f2d]">.</span></a><a className="font-mono text-xs uppercase tracking-[.18em]" href="#agendar">Agendar horário</a></header>
    <section id="inicio" className="mx-auto grid max-w-6xl gap-10 px-6 pb-24 pt-12 md:grid-cols-[1.2fr_.8fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#bd4f2d]">Barbearia de bairro, precisão de ofício</p><h1 className="mt-5 font-display text-6xl font-bold uppercase leading-[.9] md:text-8xl">Seu corte<br/><em className="font-normal text-[#bd4f2d]">no ponto.</em></h1><p className="mt-8 max-w-md text-lg leading-relaxed text-[#5b574f]">Corte, barba e cuidado sem pressa. Escolha seu serviço e reserve seu horário em poucos minutos.</p></div><aside className="border-l-4 border-[#bd4f2d] bg-[#1d1d1b] p-7 text-[#ede9e1]"><p className="font-mono text-xs uppercase tracking-[.16em]">Agora em Brasília</p><p className="mt-3 font-display text-4xl uppercase">{clock}</p><div className="mt-8 flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${isOpen ? 'bg-[#c5da6d]' : 'bg-[#bd4f2d]'}`}/><span className="font-mono text-sm uppercase">{isOpen ? 'Aberto agora' : 'Fechado agora'}</span></div><p className="mt-6 text-sm text-[#bdb7ab]">Seg–Sex · 09h às 19h<br/>Sábado e domingo · fechado</p></aside></section>
    <section className="border-y border-[#c9c1b4] bg-[#e2ddd2] py-16"><div className="mx-auto max-w-6xl px-6"><p className="font-mono text-xs uppercase tracking-[.2em]">Serviços</p><div className="mt-7 grid gap-px bg-[#c9c1b4] md:grid-cols-4">{services.map((service, i) => <div key={service.name} className="bg-[#e2ddd2] p-6"><span className="font-mono text-xs text-[#bd4f2d]">0{i + 1}</span><h2 className="mt-8 font-display text-2xl uppercase">{service.name}</h2><p className="mt-2 font-mono text-sm">{service.price}</p></div>)}</div></div></section>
    <section id="agendar" className="mx-auto grid max-w-6xl gap-12 px-6 py-24 md:grid-cols-[.7fr_1.3fr]"><div><Scissors className="text-[#bd4f2d]" size={36}/><h2 className="mt-5 font-display text-5xl uppercase leading-none">Reserve<br/>seu horário.</h2><p className="mt-5 max-w-xs text-[#5b574f]">Sem pagamento antecipado. Você paga no fim do atendimento.</p></div><form onSubmit={submit} className="grid gap-5 border-t-2 border-[#1d1d1b] pt-2"><label>Nome completo<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Telefone<input required type="tel" placeholder="(00) 00000-0000" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></label><label>Serviço<select value={form.service} onChange={e => setForm({ ...form, service: e.target.value })}>{services.map(s => <option key={s.name}>{s.name}</option>)}</select></label><label>Data e horário<input required type="datetime-local" value={form.appointmentAt} onChange={e => setForm({ ...form, appointmentAt: e.target.value })}/></label><button className="mt-3 bg-[#bd4f2d] px-6 py-4 font-mono text-sm font-bold uppercase tracking-[.15em] text-white transition hover:bg-[#913a20]">Confirmar agendamento</button>{message && <p aria-live="polite" className="text-sm">{message}</p>}</form></section>
    <section className="bg-[#1d1d1b] px-6 py-10 text-[#ede9e1]"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[.16em] text-[#c5da6d]">Onde estamos</p><h2 className="mt-3 font-display text-4xl uppercase">Venha tomar um café.</h2><p className="mt-4 text-[#bdb7ab]">Rua da Barbearia, 200 · Centro<br/>São Paulo — SP</p></div><div className="min-h-52 overflow-hidden border border-[#4b4842]"><iframe className="h-64 w-full grayscale" title="Localização da barbearia" src="https://www.google.com/maps?q=São+Paulo,+SP&output=embed" loading="lazy"/></div></div></section>
    <footer className="mx-auto flex max-w-6xl justify-between px-6 py-6 font-mono text-xs uppercase"><span>© {new Date().getFullYear()} Lâmina</span><a href="/admin">Área administrativa</a></footer>
  </main>;
}
