import { useEffect, useState } from 'react';
import { Scissors } from 'lucide-react';
import Admin from './Admin';

const api = import.meta.env.VITE_API_URL ?? '';
const MONTHS = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const services = [{ name: 'Corte clássico', price: 'R$ 45' }, { name: 'Corte + barba', price: 'R$ 75' }, { name: 'Barba completa', price: 'R$ 40' }, { name: 'Pezinho', price: 'R$ 20' }];
const phoneRegex = /^\(?\d{2}\)?\s?\d{4,5}-?\d{4}$/;
function brasiliaNow() { return new Intl.DateTimeFormat('pt-BR', { timeZone: 'America/Sao_Paulo', weekday: 'long', hour: '2-digit', minute: '2-digit' }).format(new Date()); }
function openNow() { const p = new Intl.DateTimeFormat('en-US', { timeZone: 'America/Sao_Paulo', weekday: 'short', hour: 'numeric', hour12: false }).formatToParts(new Date()); const day = p.find(x => x.type === 'weekday')?.value; const hour = Number(p.find(x => x.type === 'hour')?.value); return day !== 'Sat' && day !== 'Sun' && hour >= 9 && hour < 19; }
function daysInMonth(m: number, y: number) { return new Date(y, m + 1, 0).getDate(); }
function firstDow(m: number, y: number) { return (new Date(y, m, 1).getDay() + 6) % 7; }
function toDateStr(d: Date) { return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }
const today = new Date();
const todayStr = toDateStr(today);

export default function App() {
  if (window.location.pathname === '/admin') return <Admin />;
  const [clock, setClock] = useState(brasiliaNow()); const [isOpen, setIsOpen] = useState(openNow()); const [form, setForm] = useState({ name: '', phone: '', service: services[0].name }); const [message, setMessage] = useState(''); const [cm, setCm] = useState(today.getMonth()); const [cy, setCy] = useState(today.getFullYear()); const [sd, setSd] = useState(''); const [st, setSt] = useState(''); const [slots, setSlots] = useState<{slot_time:string}[]>([]); const [loading, setLoading] = useState(false); const [lastId, setLastId] = useState(''); const [canceling, setCanceling] = useState(false);
  useEffect(() => { const id = window.setInterval(() => { setClock(brasiliaNow()); setIsOpen(openNow()); }, 1000); return () => clearInterval(id); }, []);
  useEffect(() => { if (!sd) return; setSt(''); setLoading(true); fetch(`${api}/api/slots?date=${sd}`).then(r => r.json()).then(setSlots).finally(() => setLoading(false)); }, [sd]);
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!sd || !st) return; if (!phoneRegex.test(form.phone)) { setMessage('Telefone inválido. Use (XX) XXXXX-XXXX.'); return; } setMessage('Enviando...'); const appointmentAt = new Date(sd + 'T' + st + ':00-03:00').toISOString(); const res = await fetch(`${api}/api/appointments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, appointmentAt }) }); const data = await res.json(); if (res.ok) { setLastId(data.id); setMessage('Agendamento recebido!'); setForm({ name: '', phone: '', service: services[0].name }); setSd(''); setSt(''); } else setMessage(data.error); }
  async function cancelBooking() { if (!lastId) return; setCanceling(true); await fetch(`${api}/api/appointments/${lastId}/cancel`, { method: 'POST' }); setMessage('Agendamento cancelado.'); setLastId(''); setCanceling(false); }
  function handlePhone(e: React.ChangeEvent<HTMLInputElement>) { let v = e.target.value.replace(/[^\d()\-\s]/g, ''); const max = v.includes('(') || v.includes(')') ? 13 : 11; if (v.length > max) return; setForm({...form, phone: v}); }
  function prevMonth() { if (cm===0) { setCm(11); setCy(cy-1); } else setCm(cm-1); }
  function nextMonth() { if (cm===11) { setCm(0); setCy(cy+1); } else setCm(cm+1); }
  const dim = daysInMonth(cm, cy); const fdow = firstDow(cm, cy);
  const days: {n:number,off:boolean,ok:boolean}[] = [];
  for (let i=0; i<fdow; i++) days.push({n:0,off:true,ok:false});
  for (let d=1; d<=dim; d++) { const ds = cy+'-'+String(cm+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'); days.push({n:d,off:false,ok:ds>=todayStr}); }
  return <main>
    <header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><a className="font-display text-3xl font-bold tracking-tight" href="#inicio">LÂMINA<span className="text-[#bd4f2d]">.</span></a><a className="font-mono text-xs uppercase tracking-[.18em]" href="#agendar">Agendar horário</a></header>
    <section id="inicio" className="mx-auto grid max-w-6xl gap-10 px-6 pb-24 pt-12 md:grid-cols-[1.2fr_.8fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#bd4f2d]">Barbearia de bairro, precisão de ofício</p><h1 className="mt-5 font-display text-6xl font-bold uppercase leading-[.9] md:text-8xl">Seu corte<br/><em className="font-normal text-[#bd4f2d]">no ponto.</em></h1><p className="mt-8 max-w-md text-lg leading-relaxed text-[#5b574f]">Corte, barba e cuidado sem pressa. Escolha seu serviço e reserve seu horário em poucos minutos.</p></div><aside className="border-l-4 border-[#bd4f2d] bg-[#1d1d1b] p-7 text-[#ede9e1]"><p className="font-mono text-xs uppercase tracking-[.16em]">Agora em Brasília</p><p className="mt-3 font-display text-4xl uppercase">{clock}</p><div className="mt-8 flex items-center gap-3"><span className={`h-3 w-3 rounded-full ${isOpen ? 'bg-[#c5da6d]' : 'bg-[#bd4f2d]'}`}/><span className="font-mono text-sm uppercase">{isOpen ? 'Aberto agora' : 'Fechado agora'}</span></div><p className="mt-6 text-sm text-[#bdb7ab]">Seg–Sex · 09h às 19h<br/>Sábado e domingo · fechado</p></aside></section>
    <section className="border-y border-[#c9c1b4] bg-[#e2ddd2] py-16"><div className="mx-auto max-w-6xl px-6"><p className="font-mono text-xs uppercase tracking-[.2em]">Serviços</p><div className="mt-7 grid gap-px bg-[#c9c1b4] md:grid-cols-4">{services.map((service, i) => <div key={service.name} className="bg-[#e2ddd2] p-6"><span className="font-mono text-xs text-[#bd4f2d]">0{i + 1}</span><h2 className="mt-8 font-display text-2xl uppercase">{service.name}</h2><p className="mt-2 font-mono text-sm">{service.price}</p></div>)}</div></div></section>
    <section id="agendar" className="mx-auto grid max-w-6xl gap-12 px-6 py-24 md:grid-cols-[.7fr_1.3fr]"><div><Scissors className="text-[#bd4f2d]" size={36}/><h2 className="mt-5 font-display text-5xl uppercase leading-none">Reserve<br/>seu horário.</h2><p className="mt-5 max-w-xs text-[#5b574f]">Sem pagamento antecipado. Você paga no fim do atendimento.</p></div><form onSubmit={submit} className="grid gap-5 border-t-2 border-[#1d1d1b] pt-2"><label>Nome completo<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></label><label>Telefone<input required type="tel" placeholder="(00) 00000-0000" title="Formato: (XX) XXXXX-XXXX" value={form.phone} onChange={handlePhone}/></label><label>Serviço<select value={form.service} onChange={e => setForm({...form,service:e.target.value})}>{services.map(s => <option key={s.name} value={s.name}>{s.name} — {s.price}</option>)}</select></label>
    <label className="text-sm font-semibold">Escolha o dia</label>
    <div className="-mx-2"><div className="flex items-center justify-between mb-3"><button type="button" onClick={prevMonth} className="px-3 py-1 font-mono text-sm">&lt;</button><span className="font-display text-xl uppercase">{MONTHS[cm]}</span><button type="button" onClick={nextMonth} className="px-3 py-1 font-mono text-sm">&gt;</button></div><div className="grid grid-cols-7 gap-1 text-center">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d => <div key={d} className="font-mono text-xs text-[#5b574f] py-1">{d}</div>)}{days.map((d,i) => <button key={i} type="button" disabled={!d.ok} onClick={() => setSd(cy+'-'+String(cm+1).padStart(2,'0')+'-'+String(d.n).padStart(2,'0'))} className={`py-2 text-sm font-mono rounded transition ${d.off ? '' : !d.ok ? 'text-[#c9c1b4]' : sd===cy+'-'+String(cm+1).padStart(2,'0')+'-'+String(d.n).padStart(2,'0') ? 'bg-[#bd4f2d] text-white' : 'bg-[#c9c1b4] hover:bg-[#bdb7ab] cursor-pointer'}`}>{d.off ? '' : d.n}</button>)}</div></div>
    {sd && <><label className="text-sm font-semibold">Horários disponíveis</label><div className="flex flex-wrap gap-2">{loading ? <p className="text-sm text-[#5b574f]">Carregando...</p> : slots.length===0 ? <p className="text-sm text-[#5b574f]">Nenhum horário disponível nesta data.</p> : slots.map(s => <button key={s.slot_time} type="button" onClick={() => setSt(s.slot_time.slice(0,5))} className={`px-4 py-2 text-sm font-mono border transition ${st===s.slot_time.slice(0,5) ? 'bg-[#bd4f2d] text-white border-[#bd4f2d]' : 'border-[#1d1d1b] hover:bg-[#1d1d1b] hover:text-white'}`}>{s.slot_time.slice(0,5)}</button>)}</div></>}
    <button disabled={!sd||!st} className="mt-3 bg-[#bd4f2d] px-6 py-4 font-mono text-sm font-bold uppercase tracking-[.15em] text-white transition hover:bg-[#913a20] disabled:opacity-40">Confirmar agendamento</button>{message && <p aria-live="polite" className="text-sm">{message}</p>}{lastId && !canceling && <button type="button" onClick={cancelBooking} className="text-sm font-mono text-[#bd4f2d] underline">Cancelar agendamento</button>}{canceling && <p className="text-sm text-[#5b574f]">Cancelando...</p>}</form></section>
    <section className="bg-[#1d1d1b] px-6 py-10 text-[#ede9e1]"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[.16em] text-[#c5da6d]">Onde estamos</p><h2 className="mt-3 font-display text-4xl uppercase">Venha tomar um café.</h2><p className="mt-4 text-[#bdb7ab]">Rua da Barbearia, 200 · Centro<br/>São Paulo — SP</p></div><div className="min-h-52 overflow-hidden border border-[#4b4842]"><iframe className="h-64 w-full" title="Localização da barbearia" src="https://www.google.com/maps?q=S%C3%A3o+Paulo%2C+SP&output=embed" loading="lazy"/></div></div></section>
    <footer className="mx-auto flex max-w-6xl justify-between px-6 py-6 font-mono text-xs uppercase"><span>© {new Date().getFullYear()} Lâmina</span><a href="/admin">Área administrativa</a></footer>
  </main>;
}
